# Run Sushi to build FHIR IG

name: Run Sushi v2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run-sushi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ Now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” Branch is ${{ github.ref }} ${{ github.repository }} repo"
      - run: echo "ğŸ’¡ The ${{ github.repository }} repo has been cloned to the runner."
      
      - run: npm install
      - run: gem install jekyll
      - run: npm run sushi
      - run: yes | npm run ig_init
      - run: mkdir -p src/main/resources/hl7/fhir/alvearie/core
      - run: cp build/output/package.tgz src/main/resources/hl7/fhir/alvearie/core
      
#      - run: sudo apt install unzip
      - run: tar -xzf  src/main/resources/hl7/fhir/alvearie/core/package.tgz  -C src/main/resources/hl7/fhir/alvearie/core
      
      - run: echo "ğŸ This job's status is ${{ job.status }}."
