# This is a basic workflow to help you get started with Actions

name: Test github actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job to run sushi
  Run-sushi:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      # Runs a set of commands using the runners shell.
      - run: echo Setup checks....
      - run: echo Job was automatically triggered by a ${{ github.event_name }} event.
      - run: echo Job is now running on a ${{ runner.os }} server hosted by Github.
      - run: echo Name of the branch is ${{ github.ref }}.
      - run: echo Name of the repository is ${{ github.repository }}.

      - run: |
         echo Get IG version from json file
         githubjson='cat package.json'
         echo $githubjson
         version='echo $(jq -r 'version' <<< "$githubjson")'
         echo version
         echo 'version'
         echo $version
         
      - run: echo List files in workspace
      - run: ls ${{ github.workspace }}
      
